### ISSUE TITLE
Evaluation of Elf compression algo

### ISSUE THREAD

**Issue by iaGuoZhi** [Gyhanis/Machete#1]
Hi, Machete is an awesome project and your code is very clear to read. I saw your paper evaluated the Elf compression algo, but I didn't find the code in this repo. Could you please help me to evaluate the Elf compression algo and compare it with Machete?

**Comment by Gyhanis** [comment]
Hello. The authors of Elf published their code at https://github.com/Spatio-Temporal-Lab/elf. They implemented it in Java, and we rewrote it in C/C++ for the evaluations in our paper. I'm sorry that our lastest codes are not yet updated to this repo, and we are working on it. In case you cannot wait to evaluate Elf, I attached our Elf implementation to this answer. I believe that applying it to compression_test.cpp is easy for you.
[elf.zip](https://github.com/Gyhanis/Machete/files/13971145/elf.zip)

**Comment by iaGuoZhi** [comment]
That's really awesome, thanks!
