### ISSUE TITLE
Crash with large number of outliers

### ISSUE THREAD

**Issue by mrmbernardi** [Gyhanis/Machete#4]
If there are a large number of outliers in the data then the sizes in the header will overflow causing a crash on decompression.

For example, if I have 8190 outliers in the data then `*psize` will be set to 65536 on this line:
https://github.com/Gyhanis/Machete/blob/c977232456cef0749913120120cfe8dc11dde56e/machete/predict.cpp#L38

Then later it will be cast to 16 bits when stored in the header, storing 0:

https://github.com/Gyhanis/Machete/blob/c977232456cef0749913120120cfe8dc11dde56e/machete/machete.cpp#L74

This causes a crash later when decompressing the buffer.

**Comment by Gyhanis** [comment]
The Machete is designed for short-slice data, and outliers of more than 8190 are unexpected.
If you need to test such cases, changing the data type of header->psize to int32_t (in your local repo) should work.
It should reduce the compression ratio by only a little, especially in your cases with long data slices.
Hope this answer helps.

**Comment by mrmbernardi** [comment]
Changing the type to int32_t prevents the crash. It would be nice if Machete were to raise some sort of error in this case, so that users of the library know that compression failed.

**Comment by Gyhanis** [comment]
Good idea. We will work on that later.
